preload = /home/aatu/Downloads/wallhaven-3qrdr6.jpg
wallpaper = DP-1, /home/aatu/Downloads/wal
wallpaper {
    monitor = DP-1
    path = /home/aatu/Downloads/wallpaper1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/aatu/Downloads/wallpaper1.jpg
    fit_mode = cover
}

ipc = true

